FROM postgres:13-buster

# Python for app
ENV PYTHONDONTWRITEBYTECODE 1 \
    PYTHONUNBUFFERED 1
RUN apt-get update \
    # Can't find wheels for asyncpg for some reason :(
    && apt-get install -y libpq-dev gcc dumb-init wget curl gettext netcat \
       python3-dev python3-pip python3-setuptools \
    # && apt remove -y libpq-dev gcc \
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /example
COPY requirements.txt /example

RUN pip3 install -r /example/requirements.txt
COPY app/ /example/app/
COPY main.py /example

ENV PORT 80
ENV POSTGRES_PASSWORD=test \
    POSTGRES_USER=test \
    POSTGRES_DB=schemathesis-example \
    DATABASE_URL="postgres://test:test@localhost:5432/schemathesis-example"
EXPOSE 80

COPY start_all_services.sh /example

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["bash", "-c", "/example/start_all_services.sh"]

STOPSIGNAL SIGINT
