apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dvga.fullname" . }}
  labels:
    {{- include "dvga.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dvga.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dvga.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WEB_HOST
              value: {{ .Values.env.WEB_HOST | quote }}
            - name: WEB_PORT
              value: {{ .Values.env.WEB_PORT | quote }}
            - name: DVGA_MODE
              value: {{ .Values.gameMode | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 