# Generated by Django 3.2.25 on 2026-07-24 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_card_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('amount_value', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interval', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='month', max_length=8)),
                ('interval_count', models.IntegerField(default=1)),
                ('trial_days', models.IntegerField(default=0)),
                ('merchant_id', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_plan',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_id', models.CharField(max_length=64)),
                ('customer_email', models.CharField(blank=True, default='', max_length=128)),
                ('customer_name', models.CharField(blank=True, default='', max_length=128)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('paused', 'Paused'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='active', max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('price_override', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('discount_code', models.CharField(blank=True, default='', max_length=64)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.paymenttransaction')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.plan')),
            ],
            options={
                'db_table': 'payment_subscription',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['merchant_id', 'active'], name='pay_plan_merch_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['code'], name='pay_plan_code_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['merchant_id', 'status'], name='pay_sub_merch_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['customer_email'], name='pay_sub_email_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['plan', 'status'], name='pay_sub_plan_idx'),
        ),
    ]
