apiVersion: v1
kind: Service
metadata:
  name: crapi-payments
  labels:
    app: crapi-payments
spec:
  selector:
    app: crapi-payments
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: payments
