name: Build and release malschema images

on:
  pull_request:
    paths:
      - '.github/workflows/*-malschema-images.yml'
      - 'MalSchema/**'
  push:
    paths:
      - '.github/workflows/*-malschema-images.yml'
      - 'MalSchema/**'
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-malschema-image:
    name: Build malschema image
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: echo "MONTH=$(date +%m)" >> $GITHUB_ENV
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ github.workflow }}-${{ env.MONTH }}-{hash}
          restore-keys: |
            ${{ github.workflow }}-${{ env.MONTH }}-      

      - name: latest
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema
          path: ./MalSchema
          tag: latest
          extra_args: "--no-push"

  publish-malschema-image:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: echo "MONTH=$(date +%m)" >> $GITHUB_ENV
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ github.workflow }}-${{ env.MONTH }}-{hash}
          restore-keys: |
            ${{ github.workflow }}-${{ env.MONTH }}-

      - name: MalSchema Dockerhub push
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema
          path: ./MalSchema
          tag: latest

  build-malschema-all-image:
    name: Build malschema-all image
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: echo "MONTH=$(date +%m)" >> $GITHUB_ENV
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ github.workflow }}-${{ env.MONTH }}-{hash}
          restore-keys: |
            ${{ github.workflow }}-${{ env.MONTH }}-

      - name: latest
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema-all
          build_file: ./Dockerfile-all
          path: ./MalSchema
          tag: latest
          extra_args: "--no-push"

  publish-malschema-all-image:
    name: Publish malschema-all latest image
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: echo "MONTH=$(date +%m)" >> $GITHUB_ENV
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ github.workflow }}-${{ env.MONTH }}-{hash}
          restore-keys: |
            ${{ github.workflow }}-${{ env.MONTH }}-

      - name: latest
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema-all
          build_file: ./Dockerfile-all
          path: ./MalSchema
          tag: latest

  release-malschema-image:
    name: Build and publish MalSchema container images to DockerHub
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - run: echo "MONTH=$(date +%m)" >> $GITHUB_ENV
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
        with:
          key: ${{ github.workflow }}-${{ env.MONTH }}-{hash}
          restore-keys: |
            ${{ github.workflow }}-${{ env.MONTH }}-
            
      - name: Stable
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema
          path: ./MalSchema
          tag: stable

      - name: Versioned
        uses: aevea/action-kaniko@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image: levoai/malschema
          path: ./MalSchema
          strip_tag_prefix: v
