name: Generate crAPI load

on:
  # pull_request:
  #   paths:
  #     - .github/workflows/generate_load.yml
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  generate-crapi-load-prod:
    name: Generate crAPI load for Prod
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Load against prod Demo
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "crAPI/services/loadgen/locustfile.py"
          URL:  "https://crapi-prod-demo.levoai.app"
          USERS: "5"
          RATE: "5"
          RUNTIME: "3m"

  generate-crapi-load-dev:
    name: Generate crAPI load for Dev
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Load against Dev e2e
        uses: apardo04/locust-github-action@master
        with:
          LOCUSTFILE: "crAPI/services/loadgen/locustfile.py"
          URL:  "https://crapi-dev-spec-building.levoai.app"
          USERS: "5"
          RATE: "5"
          RUNTIME: "3m"
